/**
 * Download cart as a CSV file that opens correctly in Excel
 */
export function downloadExcel(cart, customer) {
  const { name, phone, address } = customer
  const date = new Date().toLocaleDateString('en-IN')

  const rows = []
  rows.push(['MBT BATTERY - ORDER INVOICE'])
  rows.push([])
  rows.push(['Customer:', name || '—', '', 'Date:', date])
  if (phone)   rows.push(['Phone:',   phone])
  if (address) rows.push(['Address:', address])
  rows.push([])
  rows.push(['Sr.', 'Item Code', 'Item Name', 'Quantity'])

  cart.forEach((item, i) => {
    rows.push([i + 1, item.id, item.name, item.qty])
  })

  rows.push([])
  rows.push(['', '', 'TOTAL ITEMS', cart.reduce((s, i) => s + i.qty, 0)])
  rows.push([])
  rows.push(['', '', '', 'Generated by MBT Battery App'])

  const csv = rows
    .map((row) => row.map((cell) => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(','))
    .join('\r\n')

  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `MBT_Order_${(name || 'Customer').replace(/\s+/g, '_')}_${date.replace(/\//g, '-')}.csv`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

/**
 * Open print-friendly invoice in a new tab (proper HTML, not blocked)
 */
export function printInvoice(cart, customer) {
  const { name, phone, address } = customer
  const date = new Date().toLocaleDateString('en-IN', {
    year: 'numeric', month: 'long', day: 'numeric',
  })
  const totalQty = cart.reduce((s, i) => s + i.qty, 0)

  function esc(s) {
    return String(s || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
  }

  const itemRows = cart
    .map(
      (item, i) => `
      <tr>
        <td>${i + 1}</td>
        <td><strong>${item.id}</strong></td>
        <td>${esc(item.name)}</td>
        <td style="text-align:center;">${item.qty}</td>
      </tr>`
    )
    .join('')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>MBT Battery Invoice</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: Arial, sans-serif; font-size: 12px; color: #111; padding: 28px; }
    .header {
      background: #1e40af; color: #fff;
      padding: 18px 22px; border-radius: 8px 8px 0 0;
      display: flex; justify-content: space-between; align-items: center;
    }
    .header h1 { font-size: 20px; font-weight: 800; letter-spacing: 1px; }
    .meta {
      display: flex; gap: 24px; padding: 14px 0;
      border-bottom: 2px solid #e2e8f0; margin-bottom: 16px; flex-wrap: wrap;
    }
    .meta-box { flex: 1; min-width: 180px; line-height: 1.8; }
    .meta-box strong { color: #1e40af; }
    table { width: 100%; border-collapse: collapse; margin-top: 4px; }
    th {
      background: #1e40af; color: #fff;
      padding: 10px 12px; font-size: 11px; text-align: left; font-weight: 700;
    }
    td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; font-size: 11px; }
    tr:nth-child(even) td { background: #f8fafc; }
    .tfoot-row td {
      background: #1e40af !important; color: #fff;
      font-weight: 700; font-size: 13px; padding: 12px;
    }
    .footer {
      margin-top: 20px; padding-top: 12px;
      border-top: 1px solid #e2e8f0;
      font-size: 10px; color: #94a3b8; text-align: center;
    }
    .print-btn {
      display: block; margin: 20px auto 0;
      background: #1e40af; color: #fff; border: none;
      padding: 12px 36px; border-radius: 8px;
      cursor: pointer; font-size: 14px; font-weight: 700;
    }
    @media print {
      .print-btn { display: none; }
      body { padding: 0; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🔋 MBT BATTERY</h1>
    <div style="text-align:right">
      <div style="font-size:15px;font-weight:700;">TAX INVOICE</div>
      <div style="font-size:11px;opacity:0.85;">${date}</div>
    </div>
  </div>

  <div class="meta">
    <div class="meta-box">
      <strong>Bill To:</strong><br/>
      ${esc(name || '—')}
      ${phone ? `<br/>📞 ${esc(phone)}` : ''}
      ${address ? `<br/>📍 ${esc(address)}` : ''}
    </div>
    <div class="meta-box">
      <strong>From:</strong><br/>
      MBT Battery Pvt. Ltd.<br/>
      Mobile Battery Specialists
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width:40px">Sr.</th>
        <th style="width:90px">Item Code</th>
        <th>Item Description</th>
        <th style="width:70px;text-align:center">Qty</th>
      </tr>
    </thead>
    <tbody>${itemRows}</tbody>
    <tfoot>
      <tr class="tfoot-row">
        <td colspan="3" style="text-align:right">TOTAL QUANTITY</td>
        <td style="text-align:center">${totalQty}</td>
      </tr>
    </tfoot>
  </table>

  <div class="footer">
    Thank you for your business! &bull; Generated by MBT Battery App
  </div>

  <button class="print-btn" onclick="window.print()">
    🖨️ Print / Save as PDF
  </button>
</body>
</html>`

  // Write to blob URL — works without popup blocker issues
  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.target = '_blank'
  a.rel = 'noopener'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 5000)
}
